# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/update.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.protos import common_pb2 as app_dot_protos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/protos/update.proto',
  package='jarvis.common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61pp/protos/update.proto\x12\rjarvis.common\x1a\x17\x61pp/protos/common.proto\";\n\x11GetUpdateResponse\x12&\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x18.jarvis.common.ErrorCodeb\x06proto3'
  ,
  dependencies=[app_dot_protos_dot_common__pb2.DESCRIPTOR,])




_GETUPDATERESPONSE = _descriptor.Descriptor(
  name='GetUpdateResponse',
  full_name='jarvis.common.GetUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='jarvis.common.GetUpdateResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=126,
)

_GETUPDATERESPONSE.fields_by_name['code'].enum_type = app_dot_protos_dot_common__pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['GetUpdateResponse'] = _GETUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetUpdateResponse = _reflection.GeneratedProtocolMessageType('GetUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUPDATERESPONSE,
  '__module__' : 'app.protos.update_pb2'
  # @@protoc_insertion_point(class_scope:jarvis.common.GetUpdateResponse)
  })
_sym_db.RegisterMessage(GetUpdateResponse)


# @@protoc_insertion_point(module_scope)
